name = "test-hw-12"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-hw-12_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-hw-12.wasm"
command = "npm run build:release"
